// <auto-generated />
using System;
using GeoSpot.Common.Enums;
using GeoSpot.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoSpot.Persistence.Migrations
{
    [DbContext(typeof(GeoSpotDbContext))]
    partial class GeoSpotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("geospot")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "geospot", "account_type", new[] { "user", "business" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "geospot", "gender", new[] { "not_specified", "male", "female", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "geospot", "platform", new[] { "android", "ios" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "geospot", "spot_type", new[] { "promo", "event", "news", "meetup" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoSpot.Persistence.Entities.BusinessProfileEntity", b =>
                {
                    b.Property<Guid>("BusinessProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("business_profile_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(-1)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<double>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NotificationBalance")
                        .HasColumnType("integer")
                        .HasColumnName("notification_balance");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Radius")
                        .HasColumnType("integer")
                        .HasColumnName("radius");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("BusinessProfileId")
                        .HasName("pk_business_profiles");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_business_profiles_category_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_business_profiles_user_id");

                    b.ToTable("business_profiles", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<byte[]>("IconData")
                        .HasColumnType("bytea")
                        .HasColumnName("icon_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("CategoryId")
                        .HasName("pk_categories");

                    b.ToTable("categories", "geospot");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("2a58b9ee-7f22-4df8-b5de-e38f3c3b5a09"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Еда и рестораны",
                            SortOrder = 0
                        },
                        new
                        {
                            CategoryId = new Guid("cad72e62-7293-4bf9-8a2d-178c020031e5"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Спорт",
                            SortOrder = 1
                        },
                        new
                        {
                            CategoryId = new Guid("da1cf683-2dd8-4d88-bc9c-1f0a3cff6920"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Музыка и концерты",
                            SortOrder = 2
                        },
                        new
                        {
                            CategoryId = new Guid("1ac211dc-97e0-409d-955a-6bb33c09b60f"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Кино",
                            SortOrder = 3
                        },
                        new
                        {
                            CategoryId = new Guid("0ac876bb-7930-4024-8810-a5b6f5941f94"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Шоппинг и скидки",
                            SortOrder = 4
                        },
                        new
                        {
                            CategoryId = new Guid("14dc1c16-9cb8-46fb-bd37-03ef4dfa57a6"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Вечеринки",
                            SortOrder = 5
                        },
                        new
                        {
                            CategoryId = new Guid("96eb53bd-bbe3-4b4f-a05a-8c26e29f0dfd"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Игры",
                            SortOrder = 6
                        },
                        new
                        {
                            CategoryId = new Guid("e74b5890-12db-4d0b-8db2-dbeeb8dd7f6b"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Искусство",
                            SortOrder = 7
                        },
                        new
                        {
                            CategoryId = new Guid("d7005c8c-19c8-4ec6-b9d8-1e7e31fb869c"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Образование",
                            SortOrder = 8
                        },
                        new
                        {
                            CategoryId = new Guid("6a5346dc-4606-4142-a217-d603dc687305"),
                            Color = "#FFFFFF",
                            IconData = new byte[] { 0, 1, 2, 4, 5 },
                            Name = "Другое",
                            SortOrder = 9
                        });
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.DeviceTokenEntity", b =>
                {
                    b.Property<Guid>("DeviceTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Platform>("Platform")
                        .HasColumnType("geospot.platform")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceTokenId")
                        .HasName("pk_device_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_tokens_user_id");

                    b.ToTable("device_tokens", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.ReactionTypeEntity", b =>
                {
                    b.Property<Guid>("ReactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reaction_type_id");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emoji");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("ReactionTypeId")
                        .HasName("pk_reaction_types");

                    b.ToTable("reaction_types", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotCategoryEntity", b =>
                {
                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spot_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CategoriesCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("categories_category_id");

                    b.Property<Guid>("SpotEntitySpotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spot_entity_spot_id");

                    b.HasKey("SpotId", "CategoryId")
                        .HasName("pk_spot_categories");

                    b.HasIndex("CategoriesCategoryId")
                        .HasDatabaseName("ix_spot_categories_categories_category_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_spot_categories_category_id");

                    b.HasIndex("SpotEntitySpotId")
                        .HasDatabaseName("ix_spot_categories_spot_entity_spot_id");

                    b.ToTable("spot_categories", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotCommentEntity", b =>
                {
                    b.Property<Guid>("SpotCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("spot_comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spot_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SpotCommentId")
                        .HasName("pk_spot_comments");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_spot_comments_creator_id");

                    b.HasIndex("SpotId")
                        .HasDatabaseName("ix_spot_comments_spot_id");

                    b.ToTable("spot_comments", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotEntity", b =>
                {
                    b.Property<Guid>("SpotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("spot_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid?>("BusinessProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasMaxLength(-1)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("position");

                    b.Property<int>("Radius")
                        .HasColumnType("integer")
                        .HasColumnName("radius");

                    b.Property<SpotType>("SpotType")
                        .HasColumnType("geospot.spot_type")
                        .HasColumnName("spot_type");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.HasKey("SpotId")
                        .HasName("pk_spots");

                    b.HasIndex("BusinessProfileId")
                        .HasDatabaseName("ix_spots_business_profile_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_spots_creator_id");

                    b.HasIndex("Position")
                        .HasDatabaseName("idx_spot_position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "GIST");

                    b.ToTable("spots", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotReactionEntity", b =>
                {
                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spot_id");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReactionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reaction_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SpotId", "CreatorId")
                        .HasName("pk_spot_reactions");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_spot_reactions_creator_id");

                    b.HasIndex("ReactionTypeId")
                        .HasDatabaseName("ix_spot_reactions_reaction_type_id");

                    b.ToTable("spot_reactions", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.UserCategoryEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("UserId", "CategoryId")
                        .HasName("pk_user_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_user_categories_category_id");

                    b.ToTable("user_categories", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<AccountType>("AccountType")
                        .HasColumnType("geospot.account_type")
                        .HasColumnName("account_type");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DetectionRadius")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("detection_radius");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Gender>("Gender")
                        .HasColumnType("geospot.gender")
                        .HasColumnName("gender");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<double>("LastLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("last_latitude");

                    b.Property<double>("LastLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("last_longitude");

                    b.Property<DateTime>("LocationUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("location_updated_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("password_salt");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_user_phone_number");

                    b.ToTable("users", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.UserSpotViewEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spot_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Viewed")
                        .HasColumnType("boolean")
                        .HasColumnName("viewed");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewed_at");

                    b.HasKey("UserId", "SpotId")
                        .HasName("pk_user_spot_views");

                    b.HasIndex("SpotId")
                        .HasDatabaseName("ix_user_spot_views_spot_id");

                    b.ToTable("user_spot_views", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.VerificationCodeEntity", b =>
                {
                    b.Property<Guid>("VerificationCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("verification_code_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("verification_code");

                    b.HasKey("VerificationCodeId")
                        .HasName("pk_verification_codes");

                    b.ToTable("verification_codes", "geospot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.BusinessProfileEntity", b =>
                {
                    b.HasOne("GeoSpot.Persistence.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_profiles_categories_category_id");

                    b.HasOne("GeoSpot.Persistence.Entities.UserEntity", "Creator")
                        .WithMany("BusinessProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_profiles_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.DeviceTokenEntity", b =>
                {
                    b.HasOne("GeoSpot.Persistence.Entities.UserEntity", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotCategoryEntity", b =>
                {
                    b.HasOne("GeoSpot.Persistence.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_categories_categories_categories_category_id");

                    b.HasOne("GeoSpot.Persistence.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_categories_categories_category_id");

                    b.HasOne("GeoSpot.Persistence.Entities.SpotEntity", null)
                        .WithMany()
                        .HasForeignKey("SpotEntitySpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_categories_spots_spot_entity_spot_id");

                    b.HasOne("GeoSpot.Persistence.Entities.SpotEntity", "Spot")
                        .WithMany()
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_categories_spots_spot_id");

                    b.Navigation("Category");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotCommentEntity", b =>
                {
                    b.HasOne("GeoSpot.Persistence.Entities.UserEntity", "Creator")
                        .WithMany("Comments")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_comments_users_creator_id");

                    b.HasOne("GeoSpot.Persistence.Entities.SpotEntity", "Spot")
                        .WithMany("Comments")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_comments_spots_spot_id");

                    b.Navigation("Creator");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotEntity", b =>
                {
                    b.HasOne("GeoSpot.Persistence.Entities.BusinessProfileEntity", "BusinessProfile")
                        .WithMany("Spots")
                        .HasForeignKey("BusinessProfileId")
                        .HasConstraintName("fk_spots_business_profiles_business_profile_id");

                    b.HasOne("GeoSpot.Persistence.Entities.UserEntity", "Creator")
                        .WithMany("CreatedSpots")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spots_users_creator_id");

                    b.Navigation("BusinessProfile");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotReactionEntity", b =>
                {
                    b.HasOne("GeoSpot.Persistence.Entities.UserEntity", "Creator")
                        .WithMany("Reactions")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_reactions_users_creator_id");

                    b.HasOne("GeoSpot.Persistence.Entities.ReactionTypeEntity", "ReactionType")
                        .WithMany()
                        .HasForeignKey("ReactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_reactions_reaction_types_reaction_type_id");

                    b.HasOne("GeoSpot.Persistence.Entities.SpotEntity", "Spot")
                        .WithMany("Reactions")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_reactions_spots_spot_id");

                    b.Navigation("Creator");

                    b.Navigation("ReactionType");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.UserCategoryEntity", b =>
                {
                    b.HasOne("GeoSpot.Persistence.Entities.CategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_categories_categories_category_id");

                    b.HasOne("GeoSpot.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_categories_users_user_id");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.UserSpotViewEntity", b =>
                {
                    b.HasOne("GeoSpot.Persistence.Entities.SpotEntity", "Spot")
                        .WithMany()
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_spot_views_spots_spot_id");

                    b.HasOne("GeoSpot.Persistence.Entities.UserEntity", "User")
                        .WithMany("UserSpotViews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_spot_views_users_user_id");

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.BusinessProfileEntity", b =>
                {
                    b.Navigation("Spots");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.SpotEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("GeoSpot.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("BusinessProfiles");

                    b.Navigation("Comments");

                    b.Navigation("CreatedSpots");

                    b.Navigation("DeviceTokens");

                    b.Navigation("Reactions");

                    b.Navigation("UserSpotViews");
                });
#pragma warning restore 612, 618
        }
    }
}
